modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/IBOCHELLO/timedistort-mod/issues"
[[mods]]
modId="timedistort"
version="1.0.0"
displayName="Timedistort Mod"
description='''
Timedistort mod for Minecraft 1.20.1.
'''
