name: Build Mod

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Create build/libs folder if not exists
        run: mkdir -p build/libs

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run Gradle build
        run: ./gradlew build

      - name: List build/libs contents
        run: ls -la build/libs

      - name: Upload mod jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: build/libs/*.jar
