name: Build Forge 1.20.1 Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Cache Gradle files
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Make Gradle wrapper executable
      run: chmod +x ./gradlew

    - name: Build mod
      run: ./gradlew build

    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: forge-1.20.1-mod
        path: build/libs/*.jar
