name: Build Forge 1.20.1 Mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Run Gradle build
      run: ./gradlew build --stacktrace --info

    - name: Show build/libs contents
      run: ls -l build/libs/

    - name: Upload built jar artifact
      uses: actions/upload-artifact@v4
      with:
        name: forge-mod-jar
        path: '**/build/libs/*.jar'
