name: Minecraft Forge Mod Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Kodu al
      - name: Checkout repository
        uses: actions/checkout@v4

      # Java 17 kur
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Gradle Wrapper'a çalıştırma izni ver
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Derlemeyi çalıştır
      - name: Build mod with Gradle
        run: ./gradlew build --no-daemon
        
     # Ortaya çıkan jar dosyasını artifact olarak yükle
      - name: Upload mod jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: forge-mod-jar
          path: build/libs/*.jar
