name: Build Forge Mod

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kod deposunu klonla
        uses: actions/checkout@v3

      - name: Java kurulumunu yap
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Minecraft 1.18+ için Java 17 gerekir

      - name: Gradle önbellekleme
        uses: gradle/gradle-build-action@v2

      - name: Modu derle
        run: ./gradlew build

      - name: Oluşan JAR dosyasını sakla
        uses: actions/upload-artifact@v4
        with:
          name: ForgeModJar
          path: build/libs/*.jar
