name: Minecraft Modu Oluştur

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu çek
        uses: actions/checkout@v4

      - name: Java 17 kur
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Gradlew'ye çalıştırma izni ver
        run: chmod +x gradlew

      - name: Gradle ile derle
        run: ./gradlew build --no-daemon

      - name: Artifact yükle
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: build/libs/*.jar
