name: Build Minecraft Forge Mod

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Create build/libs directory
        run: mkdir -p build/libs

      - name: Run Gradle clean build jar with debug info
        run: ./gradlew clean build jar --stacktrace --info --debug --no-daemon

      - name: List build/libs directory
        run: ls -la build/libs

      - name: Verify jar file exists
        run: |
          if ls build/libs/*.jar 1> /dev/null 2>&1; then
            echo "Jar file found."
          else
            echo "ERROR: Jar file NOT found!"
            exit 1
          fi

      - name: Upload mod jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: forge-mod-jar
          path: build/libs/*.jar
