            - adı: Bir Yapı Eseri Yükle
  kullanımlar: actions/upload-artifact@v4.6.2
  ile:
    #Eser
    isim: # isteğe bağlı, varsayılanı eserdir
    # Ne yükleneceğini açıklayan bir dosya, dizin veya joker karakter deseni
    yol:
    # Sağlanan yol kullanılarak hiçbir dosya bulunamazsa istenen davranış.
Mevcut Seçenekler:
  uyar: Bir uyarı çıkışı verir ancak eylemi başarısız kılmaz
  hata: Eylemi bir hata mesajıyla başarısız kıl
  yoksay: Herhangi bir uyarı veya hata çıkışı vermeyin, eylem başarısız olmaz

    if-no-files-found: # isteğe bağlı, varsayılan uyarıdır
    # Eserin gün cinsinden sona ereceği süre. 0, varsayılan saklamanın kullanıldığı anlamına gelir.
Minimum 1 gün. Depo ayarları sayfasından değiştirilmediği sürece maksimum 90 gün.

    saklama günleri: # isteğe bağlı
    # Zlib'in eser arşivine uygulanacağı sıkıştırma seviyesi. Değer 0 ile 9 arasında değişebilir: - 0: Sıkıştırma yok - 1: En iyi hız - 6: Varsayılan sıkıştırma (GNU Gzip ile aynı) - 9: En iyi sıkıştırma. Daha yüksek seviyeler daha iyi sıkıştırma sağlar, ancak tamamlanması daha uzun sürer. Kolayca sıkıştırılamayan büyük dosyalar için, önemli ölçüde daha hızlı yüklemeler için 0 değeri önerilir.

    sıkıştırma seviyesi: # isteğe bağlı, varsayılan 6'dır
    # Doğruysa, eşleşen ada sahip bir eser, yenisi yüklenmeden önce silinir. Yanlışsa, belirtilen ada sahip bir eser zaten mevcutsa işlem başarısız olur. Eser mevcut değilse işlem başarısız olmaz.

    üzerine yaz: # isteğe bağlı, varsayılanı false'tur
    # Doğruysa, gizli dosyalar esere dahil edilir. Yanlışsa, gizli dosyalar eserden hariç tutulur.

    include-hidden-files: # isteğe bağlı, varsayılanı false'tur
          
