name: Minecraft Modu Oluştur

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu klonla
        uses: actions/checkout@v4

      - name: Java 17'yi kur
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: gradlew için çalıştırma izni ver
        run: chmod +x gradlew

      - name: Gradle ile derle (logları göster)
        run: |
          ./grad
